### ISSUE TITLE
Upgrade `workflow.yml` actions to latest official versions

### ISSUE THREAD

**Issue by ashblue** [ashblue/oyster-package-generator#66]
`workflow.yml` should look like this. As the V2 versions of the actions are deprecated.

```
name: CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - develop
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - run: npm install
            - run: npm run build
            - name: Release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run semantic-release
```
